# training data for semantic Similarity to Fine Tune the Model.

from sentence_transformers import InputExample

train_examples = [
    # 1. College Overview
    InputExample(texts=["What is the Vision of the College?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Describe the college in brief.", "Tell me about the College."], label=1.0),
    InputExample(texts=["When was the college established?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is the motto of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What can you tell me about the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What do you can tell me about the collge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tell me somthing about the collage?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What can you say abot the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What yu can tell me about the collge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What can you tell me about colledge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could you share some information about the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can yu share sum info about teh collage?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could yu pls tel me abot the collage?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Coud you give sum informashun about the colledge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Plz share me some information of the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could yu tell me about teh colleg?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you give me info abut the colege?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could yu shar infomation about the cllege?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could yu tell me mor abot teh colg?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can yu tell me more abut the collge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Culd yu pls tell me mor abot the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tel me more about the collge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can yu tell me more about teh collge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Wat is ther to kno abot teh colledge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is thare to no abot the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Wht is ther to knw abot teh colege?", "Tell me about the College."], label=1.0),
    InputExample(texts=["What is ther to kno abot teh college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you give me details about the college?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tell me more info about teh collge?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Could you share me sum details about the collage?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can yu give me some details on tht colleg?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you give me discriptions about the colegue?", "Tell me about the College."], label=1.0),
    InputExample(texts=["Can you tell about the colleg and its deatils?", "Tell me about the College."], label=1.0),
    
    # labeling 0.0
    InputExample(texts=["What is the Vision of the College?", "What programs I can join after 12th?"], label=0.0),
    InputExample(texts=["Describe the college in brief.", "Do you offer undergraduate courses?"], label=0.0),
    InputExample(texts=["When was the college established?", "Are there any diploma programs?"], label=0.0),
    InputExample(texts=["What is the motto of the college?", "What undergraduate programs does BFGI offer after 12th?"], label=0.0),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?", "What are the arts programs available at BFGI after 12th?"], label=0.0),
    InputExample(texts=["What can you tell me about the college?", "what are the courses offered?"], label=0.0),
    InputExample(texts=["What do you can tell me about the collge?", "What are the engineering courses offered at BFGI?"], label=0.0),
    InputExample(texts=["Can you tell me somthing about the collage?", "Does BFGI offer environmental science programs?"], label=0.0),
    InputExample(texts=["Can you tell me more info about teh collge?", "How can I apply?"], label=0.0),
    InputExample(texts=["Could you share me sum details about the collage?", "What are the application deadlines?"], label=0.0),
    InputExample(texts=["Can yu give me some details on tht colleg?","Is there an online application process?"], label=0.0),
    InputExample(texts=["Can you give me discriptions about the colegue?", "Is there an entrance exam required?"], label=0.0),
    InputExample(texts=["Can you tell about the colleg and its deatils?", "Are interviews part of the admission process?"], label=0.0),
    InputExample(texts=["What is the Vision of the College?", "Does this college have a library on campus?"], label=0.3),
    InputExample(texts=["Describe the college in brief.", "Do you provide hostel facilities?"], label=0.1),
    InputExample(texts=["When was the college established?","Is there a cafeteria on campus?"], label=0.2),
    InputExample(texts=["What is the motto of the college?", "Does the college have Wi-Fi facilities?"], label=0.0),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?","What types of study spaces are available for students on campus?"], label=0.1),
    InputExample(texts=["What is the Vision of the College?", "Who is the principal of the college?"], label=0.2),
    InputExample(texts=["Describe the college in brief.", "How often do faculty members hold office hours?"], label=0.1),
    InputExample(texts=["When was the college established?","Who currentley leads the Depatment of SSD?"], label=0.1),
    InputExample(texts=["What is the motto of the college?","Who is the principal of the college?"], label=0.3),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?", "Can you tell me who the principal is?"], label=0.2),
    InputExample(texts=["What is the Vision of the College?","is there any department related to this?"], label=0.0),
    InputExample(texts=["Describe the college in brief.","Is there a Computer Science department?"], label=0.1),
    InputExample(texts=["When was the college established?","Do you have a Department of Humanities?"], label=0.2),
    InputExample(texts=["What is the motto of the college?", "How many departments have research centers or institutes?"], label=0.0),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?", "What are the departmental ranking and recognition?"], label=0.1),
    InputExample(texts=["What is the Vision of the College?","How much does a program cost"], label=0.0),
    InputExample(texts=["Describe the college in brief.", "What is the fee Structure?"], label=0.1),
    InputExample(texts=["When was the college established?","How dos the prgram cost, and how the fees are set up?"], label=0.2),
    InputExample(texts=["What is the motto of the college?","Can you tell me wut the program costs and how the feez is settup?"], label=0.3),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?","How much dos the program cost, and can you explain how the fees are sett up?"], label=0.1),
    InputExample(texts=["What is the Vision of the College?","What is the average placement percentage?"], label=0.0),
    InputExample(texts=["Describe the college in brief.","What is the highest package offered?"], label=0.1),
    InputExample(texts=["When was the college established?","What companies visit for recruitment?"], label=0.2),
    InputExample(texts=["What is the motto of the college?","Are internships provided?"], label=0.1),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?","What are the placement opportunities?"], label=0.0),
    InputExample(texts=["What is the Vision of the College?","What kind of extracurricular activities are available?"], label=0.0),
    InputExample(texts=["Describe the college in brief.","Do you organize annual events?"], label=0.1),
    InputExample(texts=["When was the college established?","Is there a cultural festival?"], label=0.2),
    InputExample(texts=["What is the motto of the college?","Do you have student clubs or societies?"], label=0.0),
    InputExample(texts=["Can you tell me about the college’s history and when it was established?","Does the college celebrate national holidays?"], label=0.3),

    # 2. Courses Offered
    InputExample(texts=["What programs I can join after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Do you offer undergraduate courses?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there any diploma programs?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Which courses at BFGI are most popular among students after 12th? ", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer science-based degree programs? ", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there any commerce-related courses at BFGI after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What are the arts programs available at BFGI after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there any professional degree programs at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What technical courses can I pursue at BFGI after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer management courses for 12th pass students? ", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What are the engineering courses offered at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI have B.Sc. programs for science students?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Can I pursue a B.Sc. in Agriculture at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there biotechnology programs available at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer a B.Sc. in Computer Science?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are medical-related courses available at BFGI after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What are the opportunities for studying physics or chemistry at BFGI?  ", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer environmental science programs?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there any forensic science courses at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Can I enroll in a B.Sc. (Hons.) program at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=[" What are the options for commerce students at BFGI after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer B.Com (Hons.) programs?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Can I pursue a degree in finance at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What accounting courses are available at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there banking and insurance courses offered at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Is there a BBA (Bachelor of Business Administration) program at BFGI?  ", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI have entrepreneurship-focused programs?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there short-term diploma programs in commerce at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What humanities courses does BFGI offer after 12th?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in English at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer psychology programs?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Can I pursue a BA in Psychology at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there journalism and mass communication courses at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["What history and political science programs are available at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Can I study sociology or anthropology at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI have programs in fine arts or design?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Are there any diploma programs in social sciences at BFGI?", "what are the courses offered?"], label=1.0),
    InputExample(texts=["Does BFGI offer a B.Tech in Computer Science?", "what are the courses offered?"], label=1.0),

    #Labeling 0.0
    InputExample(texts=["What programs I can join after 12th?","How can I apply?"], label=0.0),
    InputExample(texts=["Do you offer undergraduate courses?","what is the admission process?"], label=0.1),
    InputExample(texts=["Are there any diploma programs?","What are the application deadlines?"], label=0.2),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?", "Is there an online application process?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?","Is there an entrance exam required?"], label=0.3),
    InputExample(texts=["What programs I can join after 12th?","Does this college have a library on campus?"], label=0.0),
    InputExample(texts=["Do you offer undergraduate courses?", "What are the facilities available here?"], label=0.1),
    InputExample(texts=["Are there any diploma programs?", "Do you provide hostel facilities?"], label=0.2),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?","Is there a cafeteria on campus?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?","Does the college have Wi-Fi facilities?"], label=0.1),
    InputExample(texts=["What programs I can join after 12th?","Who is the principal of the college?"], label=0.0),
    InputExample(texts=["Do you offer undergraduate courses?","How often do faculty members hold office hours?"], label=0.1),
    InputExample(texts=["Are there any diploma programs?","Who currentley leads the Depatment of SSD?"], label=0.2),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?","Who is the principal of the college?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?","Who is Head of Department Of SSD?"], label=0.3),
    InputExample(texts=["What programs I can join after 12th?","is there any department related to this?"], label=0.0),
    InputExample(texts=["Do you offer undergraduate courses?","How many Departments do you have?"], label=0.1),
    InputExample(texts=["Are there any diploma programs?","Is there a Computer Science department?"], label=0.2),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?","Do you have a Department of Humanities?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?","How many departments have research centers or institutes?"], label=0.1),
    InputExample(texts=["What programs I can join after 12th?", "What is the fee Structure?"], label=0.0),
    InputExample(texts=["Do you offer undergraduate courses?", "How much does a program cost"], label=0.1),
    InputExample(texts=["Are there any diploma programs?", "Can you give me an idear of wut the progam cost and how the feez are set up?"], label=0.2),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?", "How dos the prgram cost, and how the fees are set up?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?","Can you tell me wut the program costs and how the feez is settup?"], label=0.1),
    InputExample(texts=["What programs I can join after 12th?", "What is the average placement percentage?"], label=0.1),
    InputExample(texts=["Do you offer undergraduate courses?","What are the placement opportunities?"], label=0.0),
    InputExample(texts=["Are there any diploma programs?","What is the highest package offered?" ], label=0.2),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?","What companies visit for recruitment?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?", "Are internships provided?"], label=0.1),
    InputExample(texts=["What programs I can join after 12th?", "What kind of extracurricular activities are available?"], label=0.0),
    InputExample(texts=["Do you offer undergraduate courses?", "Do you organize annual events?"], label=0.2),
    InputExample(texts=["Are there any diploma programs?","Is there a cultural festival?"], label=0.1),
    InputExample(texts=["What undergraduate programs does BFGI offer after 12th?", "Do you have student clubs or societies?"], label=0.0),
    InputExample(texts=["Are there any diploma courses available at BFGI after 12th?", "Does the college celebrate national holidays?"], label=0.2),
    
   
    # 3. Admissions
    InputExample(texts=["How can I apply?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What are the application deadlines?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Is there an online application process?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Is there an entrance exam required?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are interviews part of the admission process?", "what is the admission process?"], label=1.0),
    InputExample(texts=["When does the admission process start?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What is the minimum percentage/grade required for eligibility?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are there specific subjects required for eligibility?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are letters of recommendation mandatory?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can I submit additional materials like portfolios or certificates?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are my past academic achievements weighted during selection?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can I change my major after admission?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What is the grading system used?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can I defer my admission?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Is the admission process competitive?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What are the steps to apply for admission?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Where can I find the application form?", "what is the admission process?"], label=1.0),
    InputExample(texts=["When does the application process begin?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What is the deadline for submitting the application?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can I apply online or only in person?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are there any additional fees during the admission process?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What are the minimum marks required for admission?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are there specific eligibility criteria for certain programs?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can international students apply?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are working professionals eligible for admission?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can I apply if I am waiting for my final exam results?", "what is the admission process?"], label=1.0), 
    InputExample(texts=["What are the important dates for admission?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What is the policy for deferred admissions?", "what is the admission process?"], label=1.0),
    InputExample(texts=["What is the process for admission through sports quota?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Are there reserved seats for certain categories?", "what is the admission process?"], label=1.0),
    InputExample(texts=["How do I apply under the reserved category?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Is there a separate process for NRI applicants?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Who can I contact for admission-related questions?", "what is the admission process?"], label=1.0),
    InputExample(texts=["Can parents accompany students during the admission process?", "what is the admission process?"], label=1.0),
    
    #Labeling 0.0
    InputExample(texts=["How can I apply?","Does this college have a library on campus?"], label=0.0),
    InputExample(texts=["What are the application deadlines?","What are the facilities available here?"], label=0.1),
    InputExample(texts=["Is there an online application process?", "Do you provide hostel facilities?"], label=0.2),
    InputExample(texts=["Is there an entrance exam required?", "Is there a cafeteria on campus?"], label=0.0),
    InputExample(texts=["Are interviews part of the admission process?", "Does the college have Wi-Fi facilities?"], label=0.1),
    InputExample(texts=["How can I apply?", "Who is the principal of the college?"], label=0.1),
    InputExample(texts=["What are the application deadlines?", "How often do faculty members hold office hours?"], label=0.0),
    InputExample(texts=["Is there an online application process?", "Who currentley leads the Depatment of SSD?"], label=0.0),
    InputExample(texts=["Is there an entrance exam required?", "Who is the principal of the college?"], label=0.2),
    InputExample(texts=["Are interviews part of the admission process?", "Can you tell me who the principal is?"], label=0.2),
    InputExample(texts=["How can I apply?", "is there any department related to this?"], label=0.0),
    InputExample(texts=["What are the application deadlines?","How many Departments do you have?"], label=0.1),
    InputExample(texts=["Is there an online application process?", "Is there a Computer Science department?"], label=0.2),
    InputExample(texts=["Is there an entrance exam required?", "Do you have a Department of Humanities?"], label=0.1),
    InputExample(texts=["Are interviews part of the admission process?","How many departments have research centers or institutes?"], label=0.0),
    InputExample(texts=["How can I apply?","How much does a program cost"], label=0.0),
    InputExample(texts=["What are the application deadlines?","What is the fee Structure?"], label=0.1),
    InputExample(texts=["Is there an online application process?","Hey, could you give me an idea of what the program costs, and how the fees are set up?"], label=0.0),
    InputExample(texts=["Is there an entrance exam required?","Can you give me an idear of wut the progam cost and how the feez are set up?"], label=0.3),
    InputExample(texts=["Are interviews part of the admission process?","How much dos the program cost, and can you explain how the fees are sett up?"], label=0.2),
    InputExample(texts=["How can I apply?","What is the average placement percentage?"], label=0.0),
    InputExample(texts=["What are the application deadlines?", "What are the placement opportunities?"], label=0.0),
    InputExample(texts=["Is there an online application process?", "What is the highest package offered?"], label=0.1),
    InputExample(texts=["Is there an entrance exam required?", "What companies visit for recruitment?"], label=0.2),
    InputExample(texts=["Are interviews part of the admission process?", "Are internships provided?"], label=0.1),
    InputExample(texts=["How can I apply?","What kind of extracurricular activities are available?"], label=0.0),
    InputExample(texts=["What are the application deadlines?","Do you organize annual events?"], label=0.1),
    InputExample(texts=["Is there an online application process?","Is there a cultural festival?"], label=0.2),
    InputExample(texts=["Is there an entrance exam required?","Do you have student clubs or societies?"], label=0.0),
    InputExample(texts=["Are interviews part of the admission process?","Does the college celebrate national holidays?"], label=0.3),
    

    # 4. Campus Facility
    InputExample(texts=["Does this college have a library on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Do you provide hostel facilities?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a cafeteria on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have Wi-Fi facilities?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What types of study spaces are available for students on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there specialized libraries for different subjects or disciplines?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a digital or e-library for online resources and research?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there quiet study rooms or soundproof areas for focused work?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students reserve library spaces for group study sessions?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the library offer printing or scanning services?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How long can students borrow books or other materials from the library?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any extended library hours during exams or busy periods?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have a gym or fitness center for students?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any indoor or outdoor sports facilities available on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["What kind of recreational sports equipment is available for student use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a swimming pool or aquatic center on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there spaces for group fitness classes or personal training?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college offer any athletic programs or teams for students to join?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there tennis courts or basketball courts available for student use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students use the gym for free or is there a membership fee?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a running track or other outdoor exercise spaces on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there fitness-related clubs or activities organized by the college?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a computer lab available for students on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide access to computers for student use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any dedicated spaces with computers for academic work?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any labs with specialized software for students to use?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a public computer area for students who need to complete assignments?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there computers available for students to use during library hours?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have any technology resources like computer labs or digital workstations?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any computer labs with printing services on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["How many computer labs are available for students to access on campus?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students use computers in the lab for both personal and academic purposes?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college have a designated student lounge or hangout space?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any common areas where students can relax between classes?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Is there a place on campus where students can unwind or socialize?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Are there any lounges or recreational spaces for students to take a break?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Can students access any casual spaces for group discussions or relaxation?", "What are the facilities available here?"], label=1.0),
    InputExample(texts=["Does the college provide areas for students to relax and recharge?", "What are the facilities available here?"], label=1.0),

    #Labeling 0.0
    InputExample(texts=["Does this college have a library on campus?","Who is the principal of the college?"], label=0.0),
    InputExample(texts=["Do you provide hostel facilities?", "Who is Head of Department Of SSD?"], label=0.1),
    InputExample(texts=["Is there a cafeteria on campus?","How often do faculty members hold office hours?"], label=0.2),
    InputExample(texts=["Does the college have Wi-Fi facilities?","Who currentley leads the Depatment of SSD?"], label=0.0),
    InputExample(texts=["What types of study spaces are available for students on campus?","Who is the principal of the college?"], label=0.1),
    InputExample(texts=["Does this college have a library on campus?", "is there any department related to this?"], label=0.0),
    InputExample(texts=["Do you provide hostel facilities?", "How many Departments do you have?"], label=0.1),
    InputExample(texts=["Is there a cafeteria on campus?", "Is there a Computer Science department?"], label=0.2),
    InputExample(texts=["Does the college have Wi-Fi facilities?","Do you have a Department of Humanities?"], label=0.0),
    InputExample(texts=["What types of study spaces are available for students on campus?","How many departments have research centers or institutes?"], label=0.3),
    InputExample(texts=["Does this college have a library on campus?","How much does a program cost"], label=0.0),
    InputExample(texts=["Do you provide hostel facilities?", "What is the fee Structure?"], label=0.1),
    InputExample(texts=["Is there a cafeteria on campus?", "Hey, could you give me an idea of what the program costs, and how the fees are set up?"], label=0.0),
    InputExample(texts=["Does the college have Wi-Fi facilities?", "Can you give me an idear of wut the progam cost and how the feez are set up?"], label=0.2),
    InputExample(texts=["What types of study spaces are available for students on campus?","How much dos the program cost, and can you explain how the fees are sett up?"], label=0.1),
    InputExample(texts=["Does this college have a library on campus?","What is the average placement percentage?"], label=0.0),
    InputExample(texts=["Do you provide hostel facilities?","What are the placement opportunities?"], label=0.1),
    InputExample(texts=["Is there a cafeteria on campus?","What is the highest package offered?"], label=0.2),
    InputExample(texts=["Does the college have Wi-Fi facilities?","What companies visit for recruitment?"], label=0.0),
    InputExample(texts=["What types of study spaces are available for students on campus?","Are internships provided?"], label=0.0),
    InputExample(texts=["Does this college have a library on campus?","What kind of extracurricular activities are available?"], label=0.0),
    InputExample(texts=["Do you provide hostel facilities?", "Do you organize annual events?"], label=0.1),
    InputExample(texts=["Is there a cafeteria on campus?", "Is there a cultural festival?"], label=0.2),
    InputExample(texts=["Does the college have Wi-Fi facilities?","Do you have student clubs or societies?"], label=0.0),
    InputExample(texts=["What types of study spaces are available for students on campus?","Does the college celebrate national holidays?"], label=0.1),
    

    # 5. Faculty
    InputExample(texts=["Who is the principal of the college?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["How often do faculty members hold office hours?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who currentley leads the Depatment of SSD?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the principal of the college?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Can you tell me who the principal is?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who currently holds the position of principal?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the head of the college?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the current principal?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the HOD of Computer Science?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Can you tell me who the HOD of Computer Science is?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the current HOD of Computer Science?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who leads the Computer Science department?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the HOD of the Computer Science department?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the HOD of Department of Mathematics?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Can you tell me who the HOD of Mathematics is?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the current HOD of Mathematics?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who leads the Mathematics department?", "Who is Head of Department Of SSD?"], label=1.0),
    InputExample(texts=["Who is the head of the Mathematics department?", "Who is Head of Department Of SSD?"], label=1.0),

    #Labeling 0.0    
    InputExample(texts=["Who is the principal of the college?","is there any department related to this?"], label=0.1),
    InputExample(texts=["How often do faculty members hold office hours?", "How many Departments do you have?"], label=0.0),
    InputExample(texts=["Who currentley leads the Depatment of SSD?","Is there a Computer Science department?"], label=0.2),
    InputExample(texts=["Who is the principal of the college?","Do you have a Department of Humanities?"], label=0.0),
    InputExample(texts=["Can you tell me who the principal is?","How many departments have research centers or institutes?"], label=0.2),
    InputExample(texts=["Who is the principal of the college?","How much does a program cost"], label=0.0),
    InputExample(texts=["How often do faculty members hold office hours?","What is the fee Structure?"], label=0.1),
    InputExample(texts=["Who currentley leads the Depatment of SSD?", "Can you give me an idear of wut the progam cost and how the feez are set up?"], label=0.2),
    InputExample(texts=["Who is the principal of the college?", "How much dos the program cost, and can you explain how the fees are sett up?"], label=0.0),
    InputExample(texts=["Can you tell me who the principal is?","I was wondering what the program cost is and how the feees are setted up?"], label=0.3),
    InputExample(texts=["Who is the principal of the college?","What is the average placement percentage?"], label=0.0),
    InputExample(texts=["How often do faculty members hold office hours?","What are the placement opportunities?"], label=0.0),
    InputExample(texts=["Who currentley leads the Depatment of SSD?", "What is the highest package offered?"], label=0.1),
    InputExample(texts=["Who is the principal of the college?", "What companies visit for recruitment?"], label=0.2),
    InputExample(texts=["Can you tell me who the principal is?","Are internships provided?"], label=0.2),
    InputExample(texts=["Who is the principal of the college?", "What kind of extracurricular activities are available?"], label=0.0),
    InputExample(texts=["How often do faculty members hold office hours?","Do you organize annual events?"], label=0.2),
    InputExample(texts=["Who currentley leads the Depatment of SSD?","Is there a cultural festival?"], label=0.3),
    InputExample(texts=["Who is the principal of the college?","Do you have student clubs or societies?"], label=0.1),
    InputExample(texts=["Can you tell me who the principal is?","Does the college celebrate national holidays?"], label=0.0),
    
   
    # 6. Departments
    InputExample(texts=["is there any department related to this?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Is there a Computer Science department?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Do you have a Department of Humanities?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments have research centers or institutes?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments offer online or distance learning programs?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["What are the admission requirements for each department?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["What are the departmental ranking and recognition?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments offer minors or certificate programs?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Are there any departments with study abroad programs?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments have student organizations or clubs?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments offer internship or co-op programs?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Are there any departments with industry-sponsored projects?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments have advisory boards?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Are there any departments with industry partnerships for research?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Are there any departments with industry-sponsored community projects?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments have research collaborations with industry?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["Are there any departments with industry-sponsored research projects", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["What are the departmental initiatives for student innovation?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments offer innovation competitions or challenges?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How many departments offer innovation training or workshops?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How do departments collaborate with each other?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["What are the most popular departments among students?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["What role do departments play in shaping the college's strategic plan?", "How many Departments do you have?"], label=1.0),
    InputExample(texts=["How do departments support student career development?", "How many Departments do you have?"], label=1.0),

    #Labeling 0.0
    InputExample(texts=["is there any department related to this?","How much does a program cost"], label=0.0),
    InputExample(texts=["Is there a Computer Science department?", "What is the fee Structure?"], label=0.1),
    InputExample(texts=["Do you have a Department of Humanities?","Hey, could you give me an idea of what the program costs, and how the fees are set up?"], label=0.2),
    InputExample(texts=["How many departments have research centers or institutes?","Can you give me an idear of wut the progam cost and how the feez are set up?"], label=0.0),
    InputExample(texts=["How many departments offer online or distance learning programs?","How much dos the program cost, and can you explain how the fees are sett up?"], label=0.1),
    InputExample(texts=["is there any department related to this?","What is the average placement percentage?"], label=0.0),
    InputExample(texts=["Is there a Computer Science department?","What are the placement opportunities?"], label=0.1),
    InputExample(texts=["Do you have a Department of Humanities?","What is the highest package offered?"], label=0.2),
    InputExample(texts=["How many departments have research centers or institutes?","What companies visit for recruitment?"], label=0.1),
    InputExample(texts=["How many departments offer online or distance learning programs?","Are internships provided?"], label=0.0),
    InputExample(texts=["is there any department related to this?","What kind of extracurricular activities are available?"], label=0.0),
    InputExample(texts=["Is there a Computer Science department?","Do you organize annual events?"], label=0.2),
    InputExample(texts=["Do you have a Department of Humanities?","Is there a cultural festival?"], label=0.1),
    InputExample(texts=["How many departments have research centers or institutes?","Do you have student clubs or societies?"], label=0.3),
    InputExample(texts=["How many departments offer online or distance learning programs?","Does the college celebrate national holidays?"], label=0.1),

    # 7. Fees Structure
    InputExample(texts=["How much does a program cost", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Hey, could you give me an idea of what the program costs, and how the fees are set up?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you give me an idear of wut the progam cost and how the feez are set up?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["How much dos the program cost, and can you explain how the fees are sett up?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["I was wondering what the program cost is and how the feees are setted up?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you give me an idea wut the cost of program is and how the fee's is setup?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["How dos the prgram cost, and how the fees are set up?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you tell me wut the program costs and how the feez is settup?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["I’m curious—what’s the cost of the program and how is the fee structure organized?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you tell me the cost of the program and how it fees structer is organized?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["I’m wondering wut the prgram cost and how the feestructure is oragnized?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you let me know wut the cost of the prgram is and how fees structure works?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["What’s the cost of teh prgram and how the fee structure is orgnized?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you help me understand how much the program will cost, and if there are different fees for things like materials?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["What are the costs involved in the program, and how do the fees work?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["What cost’s are invloved in the program, and how do fee’s work?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can yu tell me what are the cost involved in the programe and how fee’s work?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["How much are the costs in the profram and how do the fee’s work?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["What are the fee’s that are involed in the progrem, and how do they work?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["ould yu tell me how much are the fees and what is the structure for this program?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Could yu walk me throug the fee structure, and explain how it works in this program?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["How much do I need pay to join the program, and are ther any aditional fee’s to know?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["I’d love to know more about how the fees are set up for the program. Can you explain?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you explane how the fees are setted up for the program?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["I want to know more about how the feees are structured for the profram.", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you explain to me the way fees are settup for the program?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you tel me how are the fees set for the prgram?", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["I’d like to understand how fees are arranged in the porgram.", "What is the fee Structure?"], label=1.0),
    InputExample(texts=["Can you explain me how the fee structure is put together in teh prgram?", "What is the fee Structure?"], label=1.0),

    #Labeling 0.0
    InputExample(texts=["How much does a program cost","What is the average placement percentage?"], label=0.0),
    InputExample(texts=["Hey, could you give me an idea of what the program costs, and how the fees are set up?","What are the placement opportunities?"], label=0.1),
    InputExample(texts=["Can you give me an idear of wut the progam cost and how the feez are set up?","What is the highest package offered?"], label=0.2),
    InputExample(texts=["How much dos the program cost, and can you explain how the fees are sett up?","What companies visit for recruitment?"], label=0.0),
    InputExample(texts=["I was wondering what the program cost is and how the feees are setted up?","Are internships provided?"], label=0.3),
    InputExample(texts=["How much does a program cost","What kind of extracurricular activities are available?"], label=0.1),
    InputExample(texts=["Hey, could you give me an idea of what the program costs, and how the fees are set up?","Do you organize annual events?"], label=0.0),
    InputExample(texts=["Can you give me an idear of wut the progam cost and how the feez are set up?","Is there a cultural festival?"], label=0.2),
    InputExample(texts=["How much dos the program cost, and can you explain how the fees are sett up?", "Do you have student clubs or societies?"], label=0.3),
    InputExample(texts=["I was wondering what the program cost is and how the feees are setted up?", "Does the college celebrate national holidays?"], label=0.0),
    

    # 8. Placement and Career Opportunities
    InputExample(texts=["What is the average placement percentage?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What is the highest package offered?" , "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What companies visit for recruitment?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Are internships provided?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Can you explain the placement process at the college and how students typically get ready for it?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What is the placement process followed at the college, and how do students prepare for it?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What steps are involved in the placement process at this institution?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["How does the college conduct placements, and what is expected from students during the process?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What is the procedure for campus placements, and how do students prepare themselves?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["How are placements organized at the college, and what resources are available to help students prepare?","What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Can you describe the placement process and the preparation strategies students usally follow?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the stages of the placement process at this college?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["How do students typically prepare for the placement cycle at the college?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Can you outline the steps in the placement process and how students are trainedfor it?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What proportion of students secure placements in their respective fields eachyear?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["How many students get placed annually in jobs related to their areas of study?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What is the yearly placement success rate for students in their respective disciplines?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What percentage of graduates find employment in their chosen fields after completing their studies?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["How effective is the college in ensuring students are placed in their respective domains?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What percentage of students are placed annually in their respective fields?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Are there specific eligibility criteria to participate in the placement drives?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Are there any conditions students must fulfill to qualify for placement drives?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Are certain academic or non-academic benchmarks required for placement eligibility?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the key industries visiting the campus for recruitment?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Which companies dominate the recruitment drives at this college?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Who are the most frequent recruiters at the college?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the names of the top companies that hire students here?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Which companies play a significant role in hiring graduates from this institution?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Who are the most prominent recruiters during placement drives at the college?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Which organizations consistently offer the most job opportunities to students?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Which companies are known for recruiting the highest number of students from the college?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the top hiring firms participating in the college’s placement process?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Who are the top industry players recruiting students from this institution?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What companies are most active in the campus placement program?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What kind of roles or job profiles are most commonly offered during placements?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What types of roles are typically offered to students during campus placements?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What job profiles are most in demand during the college’s placement process?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What types of jobs are most commonly available to students during placements?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Which roles do students typically get hired for during placement drives?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the usual job positions offered during campus recruitment?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What kind of career profiles are generally provided to students in placements?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the primary roles companies recruit for during the placement sessions?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the most frequent job positions offered to students during campus recruitment?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What is the highest, lowest, and average package offered to students?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What are the highest, lowest, and average salary packages offered to students during placements?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["Can you share the range of salary packages, including the highest, lowest, and average offered?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What is the average package offered to students, and how does it compare to the highest and lowest?", "What are the placement opportunities?"], label=1.0),
    InputExample(texts=["What’s the salary range offered to students, from the highest to the lowest package?", "What are the placement opportunities?"], label=1.0),
    

    # 9. Alumni Network
    InputExample(texts=["Does the college have a strong alumni network?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can alumni help students with placements?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Do alumni frequently visit the campus?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Does the college have an alumni portal?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the top achievers who graduated from this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you list any successful alumni from this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the most accomplished former students of this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which alumni from this college have made a significant impact in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most influential graduates from this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you tell me about any alumni who have become highly successfu?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which well-known people are alumni of this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share a list of famous individuals who graduated from this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent graduates from this university?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any renowned people who have walked through the halls of this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which well-known figures have attended this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent people who graduated from this institution?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What notable alumni have passed through this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you share any stories about famous people who were once students here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are the most distinguished individuals to have studied at this school?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which notable people have been part of the student body here?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any high-profile individuals who attended this college?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some prominent graduates who have had a major influence in their respective fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Can you name any alumni who have achieved great success in their careers?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Which former students have left a lasting mark on their industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some well-known alumni that have made a big impact in the professional world?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Are there any graduates who have become leaders or innovators in their fields?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["What alumni are recognized for their significant contributions to their professions?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Who are some of the most influential alumni in various industries?", "Who are some notable alumni?"], label=1.0),
    InputExample(texts=["Have any alumni from this college achieved fame in the fields of politics or business?", "Who are some notable alumni?"], label=1.0),
  
    # 10. Events and Activities
    InputExample(texts=["What kind of extracurricular activities are available?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Is there a cultural festival?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Do you have student clubs or societies?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Does the college celebrate national holidays?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What are the key annual events hosted by the college, and how are they planned?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What is the key anula events held by the collage, and how is they plannned?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Can you tell me the major anual events the collage holds, and how they are planed?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What key events does the collage holed every year, and how do they get planned?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How are the main anual events of the colledge planned, and what are they?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What are the pricipal annual events the college hold, and how they are planed?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What is the key annual event by collage, and how it is planning?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Could you tell what are the main annal events that are held by college, and how are they pland?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What r the key annual events held by collge, and how are they planned?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How do they plan the main anual events in the college, and what are they?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["What is the important anual events college hosted every year, and how are they planed?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How do students get involved in organizing the college's annual events?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How do the studnets get involved in plannning college anual evnts?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How can the students be part in the organizing of collage anual events?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Are there any special traditions or activities associated with the college’s annual events?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Can you tell me about sum of the most sucessful anual events in the past few years?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Please tell me of the most succesful annual evnts in the las few years.", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Can you tell me about some of the most succesfull anuel events in the past year?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Can yu tall me about the most succesful annual evnts of the few years past?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Could you tell me sum successful anual events of the past few yearz?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Can yu tal me about successful anuel eventz in the past few years?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How do college events and activities cater to the diverse interests of students each year?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["How do colleges eventz and actvities support divers interests of students in each year?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Are there any annual events that focus on community service or social impact?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Are ther any anual evnts that focus on community service or socail impact?", "Do you organize annual events?"], label=1.0),
    InputExample(texts=["Is ther any anual events that focuss on comunnity service or socail impact?", "Do you organize annual events?"], label=1.0),

   
    # 11. Research Opportunities
    InputExample(texts=["Does the college support research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I participate in research projects?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are research internships offered?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Does the college publish a research journal?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What types of research are being pursued in your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Could you tell me about the main focus of your lab’s research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What research projects is your lab currently working on?", "Are there any research labs ava  ilable?"], label=1.0),
    InputExample(texts=["What areas of study does your lab specialize in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you describe the research themes your lab focuses on?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What is the primary research goal in your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What kind of scientific or academic work does your lab engage in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What are the main research topics explored in your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Could you share some examples of research being conducted at your lab?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What are the key research interests of your team?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any labs that specialize in the area I am interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do you know of any research labs that focus on this topic?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any labs researching the subject I'm passionate about?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you point me to any labs that focus on this area of research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there labs that have ongoing studies in the field I'm interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any teams currently researching topics like mine?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do you have any recommendations for labs working in this area?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there a lab that is focusing on research similar to what I am interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any labs dedicated to this kind of research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can students showcase their research results at any events?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there platforms for students to share their research findings publicly?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Which labs are working on projects related to my field of interest?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do students have the chance to present their research to faculty or peers?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there an opportunity for students to give presentations on their research work?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I present my research at any college-hosted conferences or symposia?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there opportunities for undergraduates to present their research outside of class?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any avenues for students to present their research to potential employers or researchers?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What is the best way to find a faculty mentor for my research project?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I approach a professor for research mentorship?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is there a formal process for connecting with a faculty member for research mentorship?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["How can I find a professor who specializes in the area of research I am interested in?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any resources to help me find a faculty mentor for research?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is it possible for students to get their research papers published in academic journals?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Do students have the opportunity to submit research papers to journals for publication?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any opportunities for students to publish their research in journals during their studies?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Am I allowed to do independent research in the lab on my own?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can I carry out research in the lab without being part of a faculty-led project?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Is it possible to conduct my own research in the lab without a professor's supervision?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["What research facilities does this university offer?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Can you tell me about the research labs on campus?", "Are there any research labs available?"], label=1.0),
    InputExample(texts=["Are there any research departments or labs at this university?", "Are there any research labs available?"], label=1.0),


    # 12. International Collaboration
    InputExample(texts=["Does the college have international partnerships?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there opportunities to study abroad?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are foreign language courses available?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are international internships facilitated?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How can I get involoved in a student exchang prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How do I get invole in a study exhang programe?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How can I get involved in a student exchange program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How can I partcipate in a student exange progrma?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What ways can I get envolved in a stuent exchang prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How can I join a studnet exchage progarm?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What do I do to get invold in a studen exchnage program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How do I take part in a stuent exchang profram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What can I do to get inolved in student exchnge program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How can I get envolved with a study exchange prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["How do I ge involved in a stuent exchange prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What are the requirements for participating in a student exchange program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What is the requirments to participat in a studnet exchange program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there any specific qualifications needed to join a student exchange program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What do you need to partecipate in a student exchng progarm?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What is requred to take part in a studnt exchange prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What are the requiremnts for joinning a student exchange progrm?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What requirments are there for a stuent exchnage program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What is needed to get involved in a studnet exchang progarm?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What do I need to partcipate in the student exchnage prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What are the requirements for participatin in a student exchange progarm?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["What do you need to be able to join a student exchnge profram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there eny spesific qualifcations to join a student exchang program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Is there any specifc qualifications to be able to join a studnt exchange progrm?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are ther any qualifications needed to participate in student exchange profram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there spesific qualifactions need to join a studnet exchage prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are ther any specific quailfications to join a student exchnage prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there any requirments or qualfications for joing a student exchange programe?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Is ther any qualifications to join the studnet exchng prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there specific qualifycations for joining a studnet exchnge program?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Is there any qualifcations I need for joining a student exchang prgram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are ther any spesfic qualification need for participatng in student exchange profram?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Can anyone apply for a student exchange program, or are there restrictions?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Can any one appy for a student excange progrem, or are there restriction?", "Can I participate in student exchange programs?"], label=1.0),
    InputExample(texts=["Are there any restrctions on who can apply for a studnet exchange prgram?", "Can I participate in student exchange programs?"], label=1.0),

    # 13. Online Learning and Resources
    InputExample(texts=["Are online courses available?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["What e-learning tools are provided?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Is there access to virtual labs?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are students taught using online simulations?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["What online learning platforms does BFGI offer to students?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there any specific e-learning portals or LMS (Learning Management System) at BFGI?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How can students access the online library or e-resources?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Does BFGI provide access to online courses like Coursera, Udemy, or edX?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there any dedicated apps or software recommended by BFGI for learning?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are lecture recordings available for later access?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How often are online learning materials updated?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Can students access video lectures or webinars by guest speakers?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there any digital repositories for previous years’ question papers?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Is there a schedule or timetable for online classes?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are e-books and PDFs provided for all subjects?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How do students access research papers or journals online?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Does BFGI offer access to databases like IEEE, ACM, or ScienceDirect?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there any virtual labs for practical subjects?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=[" What are the steps to access BFGI’s digital library?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["What technical support is available for online learning tools?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["What technical support is available for online learning tools?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are students taught using online simulations?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Is there an IT helpdesk for resolving login or access issues?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How are issues with online portals addressed?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there tutorials for using BFGI's online learning platforms?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=[" What are the recommended devices or internet speed for online learning?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How are online assignments submitted?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["What is the process for online exams?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there mock tests or practice quizzes available online?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How are results for online assessments communicated?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are plagiarism checks conducted for online submissions?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["How can students contact professors for online doubts?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there online discussion forums for students and teachers?", "Do you offer online certification programs?"], label=1.0),
    InputExample(texts=["Are there peer study groups facilitated through online platforms?", "Do you offer online certification programs?"], label=1.0),

    
     # 14, Exams
    InputExample(texts=["How can I download the exam timetable?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the schedule for semester exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are mid-term exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the passing criteria for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How are practical exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I appear for exams if my attendance is below the required percentage?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the format of exams at BFGI (online/offline)?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What is the process to apply for re-examinations?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there any open-book exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What happens if I miss an exam due to illness?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Does BFGI provide study material for exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are mock exams conducted at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I get previous years question papers at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Are there any preparation workshops for exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I clarify doubts with faculty before exams?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Where can I collect the exam form at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I modify the details on my submitted exam form?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["When will admit cards be issued for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["How can I download my admit card?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["What should I do if theres an error on my admit card?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Is it mandatory to carry the admit card for exams at BFGI?", "What is the schedule for semester exams at BFGI?"], label=1.0),
    InputExample(texts=["Can I get a duplicate admit card if I lose the original?", "What is the schedule for semester exams at BFGI?"], label=1.0),


   # 15, GREETINGS
   InputExample(texts=["Hey, hows it goin? ", "Hi"], label=1.0),
   InputExample(texts=["Hoi, how r u doin? ", "Hi"], label=1.0),
   InputExample(texts=["Heeey, howz it going? ", "Hi"], label=1.0),
   InputExample(texts=["Hey, how’s it gon? ", "Hi"], label=1.0),
   InputExample(texts=["Hoi, hw’s it goin? ", "Hi"], label=1.0),
   InputExample(texts=["Hay, how’s it goin? ", "Hi"], label=1.0),
   InputExample(texts=["Hey, how r you going? ", "Hi"], label=1.0),
   InputExample(texts=["Heii, how goin? ", "Hi"], label=1.0),
   InputExample(texts=["Heyy, how’s goin? ", "Hi"], label=1.0),
   InputExample(texts=["Hie, howz it going? ", "Hi"], label=1.0),
   InputExample(texts=["Whts up? ", "Hi"], label=1.0),
   InputExample(texts=["Wat’s up? ", "Hi"], label=1.0),
   InputExample(texts=["Wut’s up? ", "Hi"], label=1.0),
   InputExample(texts=["Whats upp? ", "Hi"], label=1.0),
   InputExample(texts=["Whtz up? ", "Hi"], label=1.0),
   InputExample(texts=["Watz up? ", "Hi"], label=1.0),
   InputExample(texts=["Wht’s up? ", "Hi"], label=1.0),
   InputExample(texts=["Wats upp? ", "Hi"], label=1.0),
   InputExample(texts=["Wut upp? ", "Hi"], label=1.0),
   InputExample(texts=["Wat’s upp? ", "Hi"], label=1.0),
   InputExample(texts=["Howdyy!? ", "Hi"], label=1.0),
   InputExample(texts=["Howdi!? ", "Hi"], label=1.0),
   InputExample(texts=["Hooowdi!? ", "Hi"], label=1.0),
   InputExample(texts=["Hwdyy!? ", "Hi"], label=1.0),
   InputExample(texts=["Hi tehre? ", "Hi"], label=1.0),
   InputExample(texts=["Hii ther!? ", "Hi"], label=1.0),
   InputExample(texts=["Hey thare!? ", "Hi"], label=1.0),
   InputExample(texts=["Hiii tharee!? ", "Hi"], label=1.0),
   InputExample(texts=["Helo ther!? ", "Hi"], label=1.0),
   InputExample(texts=["Hi tehreee!? ", "Hi"], label=1.0),
   InputExample(texts=["Heii therre!? ", "Hi"], label=1.0),
   InputExample(texts=["Hi tbhere!? ", "Hi"], label=1.0),
   InputExample(texts=["Heey thare!? ", "Hi"], label=1.0),
   InputExample(texts=["Hii tehre!? ", "Hi"], label=1.0),
   InputExample(texts=["Yo, wuts gud? ", "Hi"], label=1.0),



   # 16. ACADEMIC_ADVISING
   InputExample(texts=["How do I choose a major?  ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=[" How many credits should I register for?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Can I change my major?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What is the process to declare a minor?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What’s the difference between a major and a minor?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I explore career options related to my major?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Can I double major?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I add or drop a class?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What are the general education requirements?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I create a four-year plan for my degree?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I know if I’m on track to graduate?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What is an academic roadmap?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Can I see a sample schedule for my major?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I balance electives with core requirements?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How can I find a faculty mentor?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Are there prerequisites for this course?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Can I take summer courses to graduate early?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What happens if I fail a class?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Can I retake a course I didn’t pass? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What is the pass/fail option, and should I consider it?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How does dropping a class affect my GPA?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I manage my time better? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=[" What study skills can I improve?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Are there resources to help me with note-taking?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I prepare for exams?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How can I deal with procrastination? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What’s the best way to balance school, work, and personal life? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Should I join a study group? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How can I improve my productivity?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I schedule my classes to avoid burnout? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Can I get help with creating a weekly study plan?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["How do I find an internship?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["Are internships required for my major? ", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=[" What’s the best way to build my resume?", "What courses should I take next semester?"], label=1.0),
   InputExample(texts=["What are the career options for my degree?", "What courses should I take next semester?"], label=1.0),

]

def get_training_data():
    """Return the training examples."""
    return train_examples

if __name__ == "__main__":
    print("This module contains intent training data for fine-tuning.")


# list all the intent here 
'''
1. COLLEGE_OVERVIEW
2.COURSES_OFFERED
3.ADMISSIONS
4.CAMPUS_FACILITY
5.FACULTY
6.DEPARTMENTS
7.FEES_STRUCTURE
8.PLACEMENT_AND_CAREER_OPPORTUNITIES
9.ALUMNI_NETWORK
10.EVENTS_AND_ACTIVITIES
11.RESEARCH_OPPORTUNITIES
12.INTERNATIONAL_COLLABORATION
13.ONLINE_LEARNING_AND_RESOURCES
14.EXAMS
15.GREETINGS
16.ACADEMIC_ADVISING


'''